apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: feckinhaproxy
spec:
  template:
    metadata:
      labels:
        app: feckinhaproxy
    spec:
      containers:
      - name: feckinhaproxy
        image: fiveateooate/feckinhaproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: 192.168.66.2 
