apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: feckinhaproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: feckinhaproxy
    spec:
      containers:
      - name: feckinhaproxy
        image: fiveateooate/feckinhaproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
