apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feckinhaproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: feckinhaproxy
    spec:
      containers:
      - image: fiveateooate/feckinhaproxy:JENKINS_BUILD_ID
        imagePullPolicy: Always
        name: feckinhaproxy
        ports:
        - containerPort: 80
      env:
        - name: ETCDHOST
          value: 192.168.66.2
        - name: ETCDPORT
          value: 2379
      nodeSelector:
        kubernetes.io/hostname: 192.168.66.2
