apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feckinhaproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: feckinhaproxy
    spec:
      hostNetwork: true
      containers:
      - name: feckinhaproxy
        image: fiveateooate/feckinhaproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /dev/log
          name: dev-log
      nodeSelector:
        kubernetes.io/hostname: 192.168.66.4 
      volumes:
      - name: dev-log
        hostPath:
          path: /dev/log 
