apiVersion: v1
kind: Service
metadata:
  labels:
    svc: feckinhaproxy
  name: feckinhaproxy
spec:
  externalIPs:
  - 192.168.66.2
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: feckinhaproxy
  type: LoadBalancer
